export const projects = [
  {
    id: "01",
    name: "Grocery Heaven", 
    timeLine: "2023", 
    githubLink: "https://github.com/naimurnemu/grocery-haven-front-end", 
    liveLink: "https://gorceryheaven.netlify.app/", 
    coverURL: "https://i.ibb.co/X7Kkbnp/grocery-Haven.png", 
    logoURL: "https://i.ibb.co/vcHbDwd/grocery-haven-Logo.png",
    caption: "Enjoy seamless shopping at Grocery Heaven, a ReactJS-powered store with multiple categories.",
    technologies: ["ReactJS", "MaterialUI", "Axios", "RestAPI", "React-Formik", "JWT", "React-Helmet", "Luxon" ],
    tools: ["Jira", "Postman", "GitHub", "Netlify"], 
    filterKeys: ["React", "Redux",],
    showCode: true,
  },
  {
    id: "02",
    name: "MedLink Jobs", 
    timeLine: "2022 - 2023", 
    githubLink: "", 
    liveLink: "https://www.medlinkjobs.com/", 
    coverURL: "https://i.ibb.co/BwCWGWn/medlink-jobs.png", 
    logoURL: "https://i.ibb.co/LgRQ2fy/Med-Link-logo.png",
    caption: "Revolutionizing healthcare recruiting with a user-friendly interface and unparalleled experience for job seekers and recruiters.",
    technologies: ["ReactJS", "MaterialUI", "GraphQL", "Base-64", "React-Helmet", "Firebase", "Moment", "swiper" ],
    tools: ["Jira", "Figma", "Slack", "Bit-Bucket"], 
    filterKeys: ["React"],
    showCode: false,
  },
  {
    id: "03",
    name: "Wisdom School", 
    timeLine: "2022", 
    githubLink: "https://github.com/naimurnemu/Wisdom-school-frontend", 
    liveLink: "https://wisdom-high-school.netlify.app/", 
    coverURL: "https://i.ibb.co/R9RYmwF/wisdom-School.jpg", 
    logoURL: "https://i.ibb.co/T84RD50/wisdomschool-logo.png",
    caption: "Enhancing the High School Experience: Dynamic site with blogs, exclusive profile, and secure Google/email login.",
    technologies: ["ReactJS", "React-bootstrap", "React-hook-form", "react-datepicker", "Font-Awesome", ],
    tools: ["Github", "Firebase", "Trello", "Netlify"], 
    filterKeys: ["React", "MERN"],
    showCode: true,
  },
]