export const projects = [
  {
    id: 100,
    name: "Penguin of Winter",
    timeLine: "2021",
    githubLink: "https://github.com/naimurnemu/tailwind-penguin",
    liveLink: "https://naimurnemu.github.io/tailwind-penguin/",
    coverURL: "https://i.ibb.co/9hL1SVZ/Penguinwinter.jpg",
    logoURL: "https://i.ibb.co/vdb2zST/Penguin-logo.png",
    caption: "A Simple template by using tailwind for occasional offers of e-commerce for more user response.",
    technologies: ["HTML5", "CSS3", "Tailwind CSS"],
    tools: ["Github", "Figma"],
    filterKeys: [],
    showCode: true,
  },
  {
    id: 101,
    name: "Camera Choice",
    timeLine: "2021",
    githubLink: "https://github.com/naimurnemu/Camera-choice-react",
    liveLink: "https://camera-choice.web.app/",
    coverURL: "https://i.ibb.co/Dbty2Pj/camera-Choice.jpg",
    logoURL: "https://i.ibb.co/mG7tRt1/Camera-Choice-logo.png",
    caption: "Enhancing e-commerce with sleek ReactJs, providing an immersive camera shopping experience with intuitive forms and dynamic user response.",
    technologies: ["ReactJS", "Material UI", "React-Router", "Context-API", "Axios", "Firebase"],
    tools: ["Github", "Firebase"],
    filterKeys: ["React", "MERN"],
    showCode: true,
  },
  {
    id: 102,
    name: "Tour Holiday",
    timeLine: "2021",
    githubLink: "https://github.com/naimurnemu/Tour-holiday-React",
    liveLink: "https://tour-holiday.web.app/",
    coverURL: "https://i.ibb.co/SdCQDwb/Tour-Holiday.jpg",
    logoURL: "https://i.ibb.co/vVFvrfp/Tour-Holiday-logo.png",
    caption: "Transforming travel dreams into reality through an immersive responsive frontend and excellent for a personalized and exclusive tourism experience.",
    technologies: ["ReactJS", "React-bootstrap", "React-Router", "Axios", "Firebase", "Font-Awesome"],
    tools: ["Github", "Firebase"],
    filterKeys: ["React", "MERN"],
    showCode: true,
  },
  {
    id: 103,
    name: "Wisdom School",
    timeLine: "2022",
    githubLink: "https://github.com/naimurnemu/Wisdom-school-frontend",
    liveLink: "https://wisdom-high-school.netlify.app/",
    coverURL: "https://i.ibb.co/R9RYmwF/wisdom-School.jpg",
    logoURL: "https://i.ibb.co/T84RD50/wisdomschool-logo.png",
    caption: "Enhancing the High School Experience: Dynamic site with blogs, exclusive profile, and secure Google/email login.",
    technologies: ["ReactJS", "React-bootstrap", "React-hook-form", "react-datepicker", "Font-Awesome"],
    tools: ["Github", "Firebase", "Trello", "Netlify"],
    filterKeys: ["React", "MERN"],
    showCode: true,
  },
  {
    id: 104,
    name: "MedLink Jobs",
    timeLine: "2022 - 2023",
    githubLink: "",
    liveLink: "https://www.medlinkjobs.com/",
    coverURL: "https://i.ibb.co/BwCWGWn/medlink-jobs.png",
    logoURL: "https://i.ibb.co/LgRQ2fy/Med-Link-logo.png",
    caption: "Revolutionizing healthcare recruiting with a user-friendly interface and unparalleled experience for job seekers and recruiters.",
    technologies: ["ReactJS", "MaterialUI", "GraphQL", "Base-64", "React-Helmet", "Firebase", "Moment", "swiper"],
    tools: ["Jira", "Figma", "Slack", "Bit-Bucket"],
    filterKeys: ["React"],
    showCode: false,
  },
  {
    id: 105,
    name: "Grocery Heaven",
    timeLine: "2023",
    githubLink: "https://github.com/naimurnemu/grocery-haven-front-end",
    liveLink: "https://gorceryheaven.netlify.app/",
    coverURL: "https://i.ibb.co/X7Kkbnp/grocery-Haven.png",
    logoURL: "https://i.ibb.co/vcHbDwd/grocery-haven-Logo.png",
    caption: "Developed a ReactJS-powered e-commerce single-page application (SPA) with multiple categories, enabling seamless customer shopping experiences.",
    technologies: ["ReactJS", "Redux", "Material UI", "Axios", "Rest API", "React-Formik", "JWT", "React-Helmet"],
    tools: ["Jira", "Postman", "GitHub", "Netlify"],
    filterKeys: ["React", "Redux"],
    showCode: true,
  },
  {
    id: 106,
    name: "Baas Brand",
    timeLine: "Feb 2024 - Oct 2024",
    githubLink: "",
    liveLink: "https://baas.manaknightdigital.com/",
    coverURL: "https://i.ibb.co.com/yS1HgpF/dashboard-wireframe.png",
    logoURL: "https://i.ibb.co.com/w7k7Hxq/manak-night.jpg",
    caption: "Developed AI-driven features like chat support, voice translation, and document handling, enhancing user interaction while streamlining cross-platform performance.",
    technologies: ["JavaScript", "React.js", "Kotlin (Android)", "AI Integration", "Jenkins", "Postman", "TreeQL", "XML", "JWT"],
    tools: ["Git", "Jira", "Firebase", "Postman", "Android Studio"],
    filterKeys: ["AI", "React", "Mobile Development"],
    showCode: false,
  },
  {
    id: 107,
    name: "Club Management",
    timeLine: "Oct 2024 - Nov 2024",
    githubLink: "https://github.com/naimurnemu/CSE_Club_University",
    liveLink: "https://computerclub-cityuniversity.netlify.app/",
    coverURL: "https://i.ibb.co.com/hsdNmxB/club-management.jpg",
    logoURL: "https://i.ibb.co.com/6PXSR2p/club-logo.png",
    caption: "Led the front-end development of a platform that connects students, faculty, and alumni, providing features like event management, voting, and collaboration tools.",
    technologies: ["JavaScript", "React.js", "Tailwind CSS", "DaisyUI", "REST APIs"],
    tools: ["Git", "Jira", "Netlify", "Figma"],
    filterKeys: ["React", "Front-End Development"],
    showCode: false,
  },
  {
    id: 108,
    name: "Department Management",
    timeLine: "Aug 2024 - Nov 2024",
    githubLink: "https://github.com/naimurnemu/Dept_manage_Frontend",
    liveLink: "https://csecityuniversity.netlify.app/",
    coverURL: "https://i.ibb.co.com/WG3cprL/department-management.png",
    logoURL: "https://csecityuniversity.netlify.app/assets/logo_cse-uPLHv7ie.png",
    caption: "Led front-end development for a dynamic web app aimed at streamlining department management with features for admins, teachers, and students.",
    technologies: ["React.js", "Material-UI", "REST APIs", "State Management"],
    tools: ["Git", "Jira", "Figma"],
    filterKeys: ["React", "State Management", "Admin Tools"],
    showCode: false,
  },
];
