export const projects = [
  {
    id: "01",
    name: "Grocery Heaven", 
    timeLine: "2023", 
    githubLink: "https://github.com/naimurnemu/grocery-haven-front-end", 
    liveLink: "https://gorceryheaven.netlify.app/", 
    coverURL: "https://i.ibb.co/X7Kkbnp/grocery-Haven.png", 
    logoURL: "https://i.ibb.co/vcHbDwd/grocery-haven-Logo.png",
    caption: "Enjoy seamless shopping at Grocery Heaven, a ReactJS-powered store with multiple categories.",
    technologies: ["ReactJS", "MaterialUI", "Axios", "RestAPI", "React-Formik", "JWT", "React-Helmet", "Luxon" ],
    tools: ["Jira", "Postman", "GitHub", "Netlify"], 
    filterKeys: ["React", "Redux-Toolkit",],
    showCode: true,
  },
  {
    id: "02",
    name: "MedLink Jobs", 
    timeLine: "2022 - 2023", 
    githubLink: "", 
    liveLink: "https://www.medlinkjobs.com/", 
    coverURL: "https://i.ibb.co/BwCWGWn/medlink-jobs.png", 
    logoURL: "https://i.ibb.co/LgRQ2fy/Med-Link-logo.png",
    caption: "Revolutionizing healthcare recruiting with a user-friendly interface and unparalleled experience for job seekers and recruiters.",
    technologies: ["ReactJS", "MaterialUI", "GraphQL", "JWT", "React-Helmet", "Luxon" ],
    filterKeys: ["React"],
    showCode: false,
  },
]